import React, { useEffect, useState } from 'react';
import { collection, deleteDoc, doc, getDocs, query, setDoc, where } from 'firebase/firestore';
import { db, provisionStaffAuth } from '../../services/firebase';
import { AlertCircle, Building2, CheckCircle2, Loader2, Pencil, Phone, Save, Trash2, Users, X } from 'lucide-react';
type Tab = 'BRANCHES' | 'STAFF' | 'EMERGENCY';
const defaults = { dashboard:false, billing:true, customers:true, salesHistory:false, products:false, purchases:false, reports:false, expenses:false, settings:false };
export function AdminManagementView({ tab }: { tab: Tab }) {
 const [rows,setRows]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState<any>(null);
 const [name,setName]=useState(''),[address,setAddress]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[branchId,setBranchId]=useState(''),[number,setNumber]=useState('');
 const branch=tab==='BRANCHES',staff=tab==='STAFF';
 async function load(){if(tab==='EMERGENCY')return;const a=await getDocs(collection(db,branch?'branches':'staff'));setRows(a.docs.map(x=>({id:x.id,...x.data()})));if(staff){const b=await getDocs(collection(db,'branches'));setBranches(b.docs.map(x=>({id:x.id,...x.data()})));}}
 useEffect(()=>{load().catch(e=>setNotice({type:'error',title:'Unable to load records',message:e.message}));},[tab]);
 function reset(){setEdit(null);setName('');setAddress('');setEmail('');setPassword('');setBranchId('');}
 function startEdit(x:any){setEdit(x);setName(x.name||'');setAddress(x.address||'');setEmail(x.email||'');setBranchId(x.branchId||'');}
 function nextId(prefix:string){const max=rows.reduce((n,x)=>{const value=prefix==='STF'?x.staffId:x.id;const m=String(value||'').match(new RegExp(`^${prefix}(\\d+)$`));return Math.max(n,m?Number(m[1]):0)},0);return `${prefix}${String(max+1).padStart(3,'0')}`;}
 async function save(){setSaving(true);try{let title='Saved successfully';if(branch){const id=edit?.id||nextId('BR');await setDoc(doc(db,'branches',id),{branchId:id,name:name.trim(),address,active:true,updatedAt:new Date().toISOString()},{merge:true});title=`${name.trim()} created successfully`;}else if(staff){const normalized=email.trim().toLowerCase();if(!normalized)throw new Error('Email is required.');const duplicate=await getDocs(query(collection(db,'staff'),where('email','==',normalized)));if(!edit&&duplicate.docs.length)throw new Error('This email is already registered. Use another email or edit the existing staff.');const id=edit?.staffId||nextId('STF');let uid=edit?.uid||edit?.id||'';if(!uid&&password)uid=await provisionStaffAuth(normalized,password);if(!uid)throw new Error('Enter password to create Firebase Auth account.');await setDoc(doc(db,'staff',uid),{staffId:id,uid,name:name.trim(),email:normalized,branchId,role:'staff',active:true,permissions:defaults,updatedAt:new Date().toISOString()},{merge:true});if(edit?.id&&edit.id!==uid)await deleteDoc(doc(db,'staff',edit.id));title=`${name.trim()} created successfully`;}else{await setDoc(doc(db,'settings','emergency'),{emergencyContactNumber:number,updatedAt:new Date().toISOString()},{merge:true});}reset();await load();setNotice({type:'success',title,message:'The record was saved securely to Firebase.'});}catch(e:any){setNotice({type:'error',title:'Could not save changes',message:e.code==='auth/email-already-in-use'?'This email is already registered in Firebase Auth.':e.message||'Save failed'});}finally{setSaving(false);}}
 function remove(x:any){setNotice({type:'confirm',title:`Delete ${x.name||x.email||x.id}?`,message:'This record will be removed from Firebase. This action cannot be undone.',onConfirm:async()=>{await deleteDoc(doc(db,branch?'branches':'staff',x.id));await load();setNotice({type:'success',title:'Deleted successfully',message:'The record was removed from Firebase.'});}});}
 const title=branch?'Branch Management':staff?'Staff Management':'Emergency Contact';const Icon=branch?Building2:staff?Users:Phone;
 return <div className="admin-page"><section className="admin-card"><header className="admin-header"><div className="admin-title"><span><Icon/></span><div><h1>{title}</h1><p>Manage your billing system configuration</p></div></div>{edit&&<button className="icon-btn" onClick={reset}><X/></button>}</header>
 {branch&&<div className="form-grid"><label>Branch ID<input className="admin-input muted" disabled value={edit?.id||'Auto-generated'}/></label><label>Branch name<input className="admin-input" placeholder="e.g. Main Branch" value={name} onChange={e=>setName(e.target.value)}/></label><label className="wide">Address<textarea className="admin-input" placeholder="Full branch address" value={address} onChange={e=>setAddress(e.target.value)}/></label></div>}
 {staff&&<div className="form-grid"><label>Staff ID<input className="admin-input muted" disabled value={edit?.id||'Auto-generated'}/></label><label>Staff name<input className="admin-input" placeholder="Staff full name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input className="admin-input" type="email" placeholder="staff@email.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input className="admin-input" type="password" placeholder="Auth password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Branch<select className="admin-input" value={branchId} onChange={e=>setBranchId(e.target.value)}><option value="">Choose branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.id} — {b.name}</option>)}</select></label></div>}
 {tab==='EMERGENCY'&&<label>Emergency contact number<input className="admin-input" placeholder="+91 XXXXX XXXXX" value={number} onChange={e=>setNumber(e.target.value)}/></label>}
 <button className="save-btn" onClick={save} disabled={saving}>{saving?<><Loader2 size={17} className="spin"/> Saving securely...</>:<><Save size={17}/> {edit?'Update':'Save'}</>}</button>
 {(branch||staff)&&<div className="row-list">{rows.map(x=><div className="data-row" key={x.id}><div><b>{x.id}</b><span>{x.name||x.email}</span><em>{x.branchId||x.address||''}</em></div><aside><button onClick={()=>startEdit(x)}><Pencil size={16}/></button><button onClick={()=>remove(x)}><Trash2 size={16}/></button></aside></div>)}</div>}</section>
 {notice&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 backdrop-blur-sm p-4"><div className="w-full max-w-md rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl"><div className="flex items-start gap-3"><div className={`rounded-xl p-3 ${notice.type==='error'?'bg-rose-500/15 text-rose-400':notice.type==='confirm'?'bg-amber-500/15 text-amber-400':'bg-emerald-500/15 text-emerald-400'}`}>{notice.type==='error'?<AlertCircle/>:notice.type==='confirm'?<Trash2/>:<CheckCircle2/>}</div><div className="flex-1"><h3 className="text-base font-bold text-white">{notice.title}</h3><p className="mt-1 text-sm text-slate-400">{notice.message}</p></div><button onClick={()=>setNotice(null)} className="text-slate-400 hover:text-white"><X size={18}/></button></div><div className="mt-6 flex justify-end gap-2">{notice.type==='confirm'?<><button onClick={()=>setNotice(null)} className="rounded-xl bg-slate-800 px-4 py-2 text-sm text-slate-300">Cancel</button><button onClick={async()=>{await notice.onConfirm();}} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-bold text-white">Delete</button></>:<button onClick={()=>setNotice(null)} className="rounded-xl bg-orange-600 px-5 py-2 text-sm font-bold text-white">Done</button>}</div></div></div>}</div>;
}
